### ISSUE TITLE
Fighter Fusion reactors are extremely inefficient

### ISSUE THREAD

**Issue by LizDragoness** [lucky-wolf/DW2-XL#15]
I feel like they are not supposed to be less efficient than antimatter or _space reactors._
edit: v2 and v3 is fine in the tech tree, it's just the first tech that has that weird number.

![image](https://user-images.githubusercontent.com/123353916/227706464-358df7af-e04c-4a02-bc9f-5e7cdc16140f.png)
![image](https://user-images.githubusercontent.com/123353916/227706481-336c1ba2-aa76-483c-8a8c-238688fa3c74.png)
![image](https://user-images.githubusercontent.com/123353916/227706496-e78eb389-171e-4ebb-a5bd-b4f64b27f4b8.png)

**Comment by lucky-wolf** [comment]
You're entirely correct.

However, no fuel is actually used for FTR/BMR at all.  No resources of any kind are tracked by the game engine.
The only thing that matters is energy output - possibly overall range, but I very much doubt it - I've never seen fighters limited by fuel capacity.

In an ideal world, I'd fix this so that the numbers LOOK right.  But in this world, with so many other things to focus for a greater value outcome, it's unlikely I'll do anything about this.

If you want to do the work, and submit the XML changes here, I would incorporate them.  Up to you!

**Comment by lucky-wolf** [comment]
Hey - I finally got back to updating ftr reactors - and they're now all in line with the same efficiency of their standard starship brethren.  So Fusion  start at 1.5 per 1000, and get better, at the same rate as you see for ship's reactors.
